{
  "cveId": "CVE-2025-58047",
  "eventName": "New CVE Received",
  "cveChangeId": "748AFE67-CFCE-4E47-95F4-82F56E40F054",
  "sourceIdentifier": "security-advisories@github.com",
  "created": "2025-08-28T18:15:33.277",
  "details": [
    {
      "action": "Added",
      "type": "Description",
      "newValue": "Volto is a React based frontend for the Plone Content Management System. In versions from 19.0.0-alpha.1 to before 19.0.0-alpha.4, 18.0.0 to before 18.24.0, 17.0.0 to before 17.22.1, and prior to 16.34.0, an anonymous user could cause the NodeJS server part of Volto to quit with an error when visiting a specific URL. The problem has been patched in versions 16.34.0, 17.22.1, 18.24.0, and 19.0.0-alpha.4. To mitigate downtime, have setup automatically restart processes that quit with an error."
    },
    {
      "action": "Added",
      "type": "CVSS V3.1",
      "newValue": "AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    },
    {
      "action": "Added",
      "type": "CWE",
      "newValue": "CWE-755"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/plone/volto/commit/2789a287ac45ad9039fb9161d465ba13241fff0a"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/plone/volto/releases/tag/16.34.0"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/plone/volto/releases/tag/17.22.1"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/plone/volto/releases/tag/18.24.0"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/plone/volto/releases/tag/19.0.0-alpha.4"
    },
    {
      "action": "Added",
      "type": "Reference",
      "newValue": "https://github.com/plone/volto/security/advisories/GHSA-xjhf-7833-3pm5"
    }
  ]
}