{
  "cveId": "CVE-2020-36794",
  "eventName": "New CVE Received",
  "cveChangeId": "4EB243D4-2B30-43EE-90C1-59B5B322C059",
  "sourceIdentifier": "416baaa9-dc9f-4396-8d5f-8c081fb06d67",
  "created": "2025-09-16T16:15:37.177",
  "details": [
    {
      "action": "Added",
      "type": "Description",
      "newValue": "Rejected reason: ** REJECT ** DO NOT USE THIS CVE RECORD. ConsultIDs: none. Reason: This record was in a CNA pool that was not assigned to any issues during 2020. Notes: none."
    }
  ]
}