{
  "cveId": "CVE-2020-36802",
  "eventName": "New CVE Received",
  "cveChangeId": "E5F5AE54-A871-4FD5-AE0F-5126F84BF0C0",
  "sourceIdentifier": "416baaa9-dc9f-4396-8d5f-8c081fb06d67",
  "created": "2025-09-16T16:15:37.700",
  "details": [
    {
      "action": "Added",
      "type": "Description",
      "newValue": "Rejected reason: ** REJECT ** DO NOT USE THIS CVE RECORD. ConsultIDs: none. Reason: This record was in a CNA pool that was not assigned to any issues during 2020. Notes: none."
    }
  ]
}