{
  "cveId": "CVE-2019-25184",
  "eventName": "New CVE Received",
  "cveChangeId": "1C7940CC-85AB-4D64-BFB7-ABA9F1160BDF",
  "sourceIdentifier": "416baaa9-dc9f-4396-8d5f-8c081fb06d67",
  "created": "2025-09-16T16:15:35.313",
  "details": [
    {
      "action": "Added",
      "type": "Description",
      "newValue": "Rejected reason: ** REJECT ** DO NOT USE THIS CVE RECORD. ConsultIDs: none. Reason: This record was in a CNA pool that was not assigned to any issues during 2019. Notes: none."
    }
  ]
}