{
  "cveId": "CVE-2025-8812",
  "eventName": "Initial Analysis",
  "cveChangeId": "504C63CA-3E7F-4B61-90E0-9A7E2E0AF074",
  "sourceIdentifier": "nvd@nist.gov",
  "created": "2025-09-02T18:41:16.390",
  "details": [
    {
      "action": "Added",
      "type": "CVSS V3.1",
      "newValue": "AV:N/AC:L/PR:L/UI:R/S:C/C:L/I:L/A:N"
    },
    {
      "action": "Added",
      "type": "CPE Configuration",
      "newValue": "OR\n          *cpe:2.3:a:pybbs_project:pybbs:*:*:*:*:*:*:*:* versions up to (including) 6.0.0"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "VulDB: https://github.com/atjiu/pybbs/commit/2fe4a51afbce0068c291bc1818bbc8f7f3b01a22 Types: Patch"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "VulDB: https://github.com/atjiu/pybbs/issues/209 Types: Exploit, Issue Tracking"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "VulDB: https://github.com/atjiu/pybbs/issues/209#issuecomment-3134772651 Types: Issue Tracking"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "VulDB: https://vuldb.com/?ctiid.319341 Types: Permissions Required, VDB Entry"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "VulDB: https://vuldb.com/?id.319341 Types: Third Party Advisory, VDB Entry"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "VulDB: https://vuldb.com/?submit.622331 Types: Third Party Advisory, VDB Entry"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "CISA-ADP: https://github.com/atjiu/pybbs/issues/209#issuecomment-3134772651 Types: Issue Tracking"
    },
    {
      "action": "Added",
      "type": "Reference Type",
      "newValue": "CISA-ADP: https://github.com/atjiu/pybbs/issues/209 Types: Exploit, Issue Tracking"
    }
  ]
}